package_path: javascripts
compress_assets: off
embed_assets: off
gzip_assets: off
template_function: Handlebars.compile
template_extension: ms

javascripts:
  travis:
    - public/javascripts/vendor/jquery*.js
    - public/javascripts/vendor/underscore*.js
    - public/javascripts/vendor/**/*.js
    - public/javascripts/application.js
    - public/javascripts/lib/**/*.js
    - public/javascripts/app/**/*.js
  travis_mobile:
    - public/javascripts/mobile/lib/zepto.js # Needed to be compiled before backbone
    - public/javascripts/mobile/lib/underscore.js # Needed to be compiled before backbone
    - public/javascripts/mobile/lib/*.js
    - public/javascripts/mobile/application.js
    - public/javascripts/mobile/app/models/*.js
    - public/javascripts/mobile/app/**/*.js
    - public/javascripts/mobile/app/templates/**/*.ms
  user_profile:
    - public/javascripts/user_profile_page.js

  templates:
    - public/javascripts/app/templates/**/*.ms
  jasmine:
    - public/javascripts/tests/vendor/jasmine.js
    - public/javascripts/tests/vendor/**/*.js
    - public/javascripts/tests/test_helper/**/*.js
    - public/javascripts/tests/**/*.js
  capybara:
    - public/javascripts/mock/pusher_mock.js
